###################################################
# Section to setup necessary env vars and overrides

EXPAND = ENV['CUKE_EXPAND'] ? "--expand" : ""

COLOR = ENV['FORCE_COLOR'] ? "-c" : ""

OTHER_TAGS = ENV['OTHER_TAGS'] ? "--tags "+ENV['OTHER_TAGS'] : ""

#######################################################

$SUCCESS=true
$failures = Hash.new

#######################################################################################################
# Helper defs

# This method is to run a given test or set of tests that have a dependency on a fixture being loaded
# Inputs: (String) testDirPath = path to a directory of tests or a single feature file (starting in acceptance-tests directory)
# Inputs: (String) collectionName = name of mongo collection to load fixture data to
# Inputs: (String) fixtureFileName = name of json file in the test/data folder
def runFixtureAndTests(testDirPath, collectionName, fixtureFileName)
  setFixture(collectionName,fixtureFileName) {runTests(testDirPath)}
end

# This method is to run a given test of set of test where a fixture is not needed
# Inputs: (String) testDirPath = path to a directory of tests or a single feature file (starting in acceptance-tests directory)
def runTests(testDirPath)
  sh "cucumber #{testDirPath} #{EXPAND} --tags ~@wip #{OTHER_TAGS} #{COLOR} -f junit --out ./target -f pretty" do |success, exit_code|
    if success
      $failures[testDirPath[testDirPath.rindex('/')+1..-1]] = "Passed"
    else
      $failures[testDirPath[testDirPath.rindex('/')+1..-1]] = "Failed"
      $SUCCESS=false
    end
  end
end



def displayFailureReport()
  startRed = "\e[31m"
  startGreen = "\e[32m"
  colorReset = "\e[0m"
  
  $failures.each do |key, value|
    if ENV['FORCE_COLOR']
      puts "#{startRed}#{key} tests #{value}#{colorReset}" if value == "Failed"
      puts "#{startGreen}#{key} tests #{value}#{colorReset}" if value == "Passed"
    else
      puts "#{key} tests #{value}"
    end
    
  end
end

############################################################################################################


######################################################################################################
# Rake tasks


desc "Run Portal Tests"
task :portalTests => [:portalAdminTests,
                      :portalEducatorTests,
                      :portalEulaTests,
                      :portalReportAProblemTests,
                      :portalAdminPageTests,
                      :portalEducatorLoginTests,
                      :portalWsrpTests,
                      :portalHeaderFooterTests] do
  displayFailureReport()
  if $SUCCESS
    puts "Completed All Tests"
  else
    raise "Tests have failed"
  end
end

###########################################################
#SLI Liferay testing
###########################################################

desc "Run Portal Admin Test"
task :portalAdminTests do
   runTests("features/liferay/SLI_admin.feature")
end

desc "Run Portal Educator Test"
task :portalEducatorTests do
   runTests("features/liferay/SLI_normal_user.feature")
end

desc "Run Eula Test"
task :portalEulaTests do
   #runTests("features/liferay/NY_Realm_EULA_agree.feature")
end

desc "Run Report A Problem Test"
task :portalReportAProblemTests do
   runTests("features/liferay/report_problem.feature")
end

desc "Run Admin Page Test"
task :portalAdminPageTests do
   runTests("features/liferay/admin_page.feature")
end

desc "Run Eduator Test"
task :portalEducatorLoginTests do
   runTests("features/liferay/SSD_Realm_linda.feature")
end

desc "Run WSRP Test"
task :portalWsrpTests do
   runTests("features/liferay/WSRP.feature")
end

desc "Run Header and Footer Test"
task :portalHeaderFooterTests do
   runTests("features/liferay/Header_footer.feature")  
end

desc "Run Eula Agreement Test"
task :portalEulaAgreementTests do
# runTests("test/features/liferay/IL_Realm_EULA_agree.feature")
end
